server:
  port: 8080

spring:
  application:
    name: nx-search-server
  profiles:
    active: dev # 默认激活application-dev.yml配置
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# ===================================================================
# mybatis配置，包括分页插件配置如下
# ===================================================================
mybatis:
    type-aliases-package: com.nx.search.model
    mapper-locations: classpath:mapper/*.xml

# ===================================================================
# kaptcha配置，验证码
# ===================================================================
kaptcha:
  border:
    color: 105,179,90
  textproducer:
    font:
      color: blue
      names: 宋体,楷体,微软雅黑
    char:
      length: 4
  image:
    width: 150
    height: 50
  session:
    key: code